# Generated by Django 3.2.4 on 2021-07-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0007_auto_20210721_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkshake',
            old_name='uid',
            new_name='mid',
        ),
        migrations.RenameField(
            model_name='snack',
            old_name='uid',
            new_name='snid',
        ),
        migrations.RenameField(
            model_name='sweet',
            old_name='uid',
            new_name='sid',
        ),
    ]
