# Generated by Django 3.2.4 on 2021-07-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
