# Generated by Django 3.2.4 on 2021-07-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0011_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy',
        ),
    ]
